### ISSUE TITLE
Orchestrate Apache Spark YAML Bug Fix

### ISSUE THREAD

**Issue by ghunkins** [sigopt/sigopt-examples#111]
I tried to open PR to put out a tiny bug-fix for the file [`orchestrate/apache_spark/orchestrate.yml`](https://github.com/sigopt/sigopt-examples/blob/master/orchestrate/apache_spark/orchestrate.yml), but I got a `<403>` when I tried to push the branch. 🔒So I'll just post it here!

The following line:

```yaml
repository: orchestrate/spark-example
```
should be replaced with
```yaml
aws:
  ecr:
    repository: orchestrate/spark-example
```
After that example works brilliantly. 🎉 

cc: @alexandraj777 @benhsu75 @dclayh
